[package]
name = "cash-me-if-you-can"
version = "0.1.0"
authors = ["Sriakhil Gogineni"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
